description: TrOCR fine-tuned
tags:
  - trocr
  - small
params:
  model: trocr-small-handwritten
  batch-size: 8
  validation-batch-size: 16
  prediction-batch-size: 16
  max-epochs: 10
  patience: 2
  lr: 2e-05
  warmup-init-lr: 1e-8
  warmup-updates: 500
  weight-decay: 0.0001
  beam: 10
